name: Backend Continuous Integration

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  # Linting Job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.9'
      - name: Install pipenv
        run: pip install pipenv
 
      - name: Install dependencies
        run: pipenv install
        working-directory: ./starter/backend

      - name: Run linter
        run: pipenv run flake8 .
        working-directory: ./starter/backend

  # test Job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.9'
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install
        working-directory: ./starter/backend

      - name: Run tests
        run: pipenv run test
        working-directory: ./starter/backend

  # Build Job
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.9'
    
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install
        working-directory: ./starter/backend

      - name: Build with Docker
        run: |
          docker build -t my-app .
        working-directory: ./starter/backend
