name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Linting Job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: ./starter/backend

      - name: Run linter
        run: pipenv run flake8 .
        working-directory: ./starter/backend

  # Testing Job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: ./starter/backend

      - name: Run tests
        run: pipenv run test
        working-directory: ./starter/backend

  # Build and Deploy Job
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
         version: 'v1.27.0' # default is latest stable
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: backend
            IMAGE_TAG: ${{ github.sha }}
        run: |
         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        working-directory: ./starter/backend

      - name: Substitute variables in deployment.yaml
        env:
          CONTAINER_NAME: backend
          IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}
        run: |
          envsubst < ./starter/backend/deployment.yaml > ./starter/backend/deployment-subst.yaml

      - name: Update kube config
        run: aws eks update-kubeconfig --name cluster
        working-directory: ./starter/backend

      - name: Deploy to EKS
        run: |
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml
        working-directory: ./starter/backend/k8s/